<a href="https://colab.research.google.com/github/1PD-IS-NO-1/mlproject/blob/main/NUMPY_LIBRARY_PRACTICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
lst = [1,2,3,4]
arr = np.array(lst)
print(arr)
arr   # it did not give me any output, if you do print then it give you give you outp
print(type(arr))
arr.shape

[1 2 3 4]
<class 'numpy.ndarray'>


(4,)

In [ ]:
arr


array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
lst2 = ([[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]])
arr2 = np.array(lst2)
print(arr2)
print(type(arr2))
arr2.shape



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


(3, 4)

In [ ]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2[0:,3:]

array([[ 4],
       [ 8],
       [12]])

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

arr1 = np.arange(9)
print(arr1)
#iwant = arr1.copy
#print(iwant)




In [ ]:
iwant = arr1.copy
iwant

<function ndarray.copy>

In [ ]:
val = 3
print(arr1<3)

[ True  True  True False False False False False False]


In [ ]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr1 = np.arange(9)
arr2 = np.arange(9)
arr = arr1*arr2
arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [ ]:
np.ones((2,3),dtype= int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.random.rand(3,3)

array([[0.06926125, 0.36234649, 0.32173888],
       [0.5374477 , 0.13612148, 0.12373795],
       [0.67170469, 0.04330698, 0.93020782]])

In [ ]:
arr_ex =np.random.randn(4,3)
arr_ex

array([[-0.08583521,  0.74391825,  2.08050518],
       [-0.63189791, -1.48164424,  0.36035695],
       [-0.00374983, -0.6871148 , -0.72042155],
       [ 0.0450541 ,  1.79964291, -0.04279838]])

In [ ]:
np.random.randint(0,100,(2,8))

array([ 4, 94,  1, 63, 86, 46, 70, 53])

In [ ]:
np.random.randint(0,100,(2,8))

array([[95, 20,  8, 48, 31, 38, 99, 49],
       [40, 67, 72, 22,  9,  1, 12, 86]])

In [ ]:
np.random.random_sample((5,8))


array([[0.71375873, 0.5311686 , 0.43826831, 0.83247825, 0.69645309,
        0.95876282, 0.02214159, 0.56114148],
       [0.81060924, 0.45401177, 0.86640771, 0.06258328, 0.82963954,
        0.35616531, 0.21233916, 0.95987154],
       [0.02801036, 0.68945053, 0.9678056 , 0.17123516, 0.95218531,
        0.42561122, 0.64249675, 0.41566308],
       [0.30730094, 0.29908312, 0.24055741, 0.37895357, 0.83221768,
        0.83612128, 0.94756948, 0.75113524],
       [0.56033753, 0.54036927, 0.22915813, 0.84340436, 0.52651664,
        0.12099529, 0.60995666, 0.27518271]])