<a href="https://colab.research.google.com/github/1PD-IS-NO-1/mlproject/blob/main/Pandas_Library_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(5,4),index=['row1','row2','row3','row4','row5',],columns=['column1','column2','column3','column4'])
df
# here you can (20) as (0,20) but output will be sane

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df.loc['row1']

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int64

In [ ]:
type(df.loc['row1'])

pandas.core.series.Series

In [ ]:
df.iloc[0:3,0:3]

column1  column2  column3
row1        0        1        2
row2        4        5        6
row3        8        9       10

In [ ]:
type(df.iloc[0:3,0:3])

pandas.core.frame.DataFrame

In [ ]:
# take the all element of coloumn 2
df.iloc[0:,1:2]


column2
row1        1
row2        5
row3        9
row4       13
row5       17

In [ ]:
#convert dataframe into array
df.iloc[0:4,0:4].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
df.isnull().sum()
#''' df.isnull() creates a DataFrame of the same shape as df where each element is True if the corresponding element in df is NaN (missing),
# and False otherwise.
#.sum() then sums up the True values (which represent missing values) in each column, effectively counting how many missing values there are in each column.

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [ ]:
df.isnull()

column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False

In [ ]:
df.head()
# ye wala uper wala df ke liye hai jo uper hi uper define kiya hai

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df['column2']
#so it give you all element of column 2
# you can put multiple column in this and it giveyou that column

row1     1
row2     5
row3     9
row4    13
row5    17
Name: column2, dtype: int64

In [ ]:
df['column2'].value_counts()
#it counts repetation of all number in specific column

1     1
5     1
9     1
13    1
17    1
Name: column2, dtype: int64

In [ ]:
df.index
# so by this way you can find the name of all row

Index(['row1', 'row2', 'row3', 'row4', 'row5'], dtype='object')

In [ ]:
# so by this way you can find the name of all column
df.columns

Index(['column1', 'column2', 'column3', 'column4'], dtype='object')

In [ ]:
arr=np.random.randn(5,3)
arr

array([[ 0.45753818,  0.73265339,  1.58161087],
       [ 0.42470985,  0.98808641,  1.1225755 ],
       [ 0.10203958, -0.80605931,  0.91763445],
       [ 0.80150481,  0.52714697,  0.64614272],
       [-1.13937756,  0.75793533,  1.1633872 ]])

In [ ]:
pd.DataFrame(arr)

0         1         2
0  0.457538  0.732653  1.581611
1  0.424710  0.988086  1.122575
2  0.102040 -0.806059  0.917634
3  0.801505  0.527147  0.646143
4 -1.139378  0.757935  1.163387

In [ ]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],
                     columns=['one', 'two', 'three'])
df.head()

one       two     three
a -0.373147  0.811304  0.282993
c -0.770485 -1.077955  2.122922
e -0.202003 -0.315119  0.331111
f  0.699706 -0.837724  0.600010
h -0.250824 -1.211814 -1.172483

In [ ]:
df.dropna(axis=0)

one       two     three
a -0.373147  0.811304  0.282993
c -0.770485 -1.077955  2.122922
e -0.202003 -0.315119  0.331111
f  0.699706 -0.837724  0.600010
h -0.250824 -1.211814 -1.172483

In [ ]:
df2 = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df2

one       two     three
a -0.373147  0.811304  0.282993
b       NaN       NaN       NaN
c -0.770485 -1.077955  2.122922
d       NaN       NaN       NaN
e -0.202003 -0.315119  0.331111
f  0.699706 -0.837724  0.600010
g       NaN       NaN       NaN
h -0.250824 -1.211814 -1.172483

In [ ]:
df2.dropna(axis=0)

one       two     three
a -0.373147  0.811304  0.282993
c -0.770485 -1.077955  2.122922
e -0.202003 -0.315119  0.331111
f  0.699706 -0.837724  0.600010
h -0.250824 -1.211814 -1.172483

In [ ]:
pd.isna(df2['one'])

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [ ]:
df2['one'].notna()
# it give True if row doesn't have NaNa otherwise it give False

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: one, dtype: bool

In [ ]:
df2.fillna('Missing')

one       two     three
a -0.373147  0.811304  0.282993
b   Missing   Missing   Missing
c -0.770485 -1.077955  2.122922
d   Missing   Missing   Missing
e -0.202003 -0.315119  0.331111
f  0.699706 -0.837724   0.60001
g   Missing   Missing   Missing
h -0.250824 -1.211814 -1.172483

In [ ]:
df2['two'].values
# It returns a NumPy array containing the values for specific column here wechoose two

array([ 0.81130411,         nan, -1.07795543,         nan, -0.31511866,
       -0.83772418,         nan, -1.2118137 ])

In [ ]:
from io import StringIO, BytesIO

In [ ]:
data = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [ ]:
type(data)

str

In [ ]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [ ]:
## Read from specific columns
df=pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in ['COL1', 'COL3'])

In [ ]:
df.to_csv('Test.csv')
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Specifying columns data types

data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [ ]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [ ]:
df=pd.read_csv(StringIO(data), )

In [ ]:
df

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [ ]:
df['a'][1]

'5'

In [ ]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'a':'Int64'})

<ipython-input-65-fffbb3ed08c5>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df=pd.read_csv(StringIO(data),dtype={'b':int,'c':np.float,'a':'Int64'})


In [ ]:
df

In [ ]:
df['a'][1]

5

In [ ]:
# check the datatype
df.dtypes

a      Int64
b      int64
c    float64
d    float64
dtype: object

In [ ]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [ ]:
pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [ ]:
 data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')

In [ ]:

pd.read_csv(StringIO(data))

a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [ ]:
pd.read_csv(StringIO(data),index_col=False)

In [ ]:
## Combining usecols and index_col
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')

In [ ]:
pd.read_csv(StringIO(data), usecols=['b', 'c'],index_col=False)

In [ ]:
## Quoting and Escape Characters¶. Very useful in NLP

data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [ ]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [ ]:
## URL to CSV

df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',
                 sep='\t')

HTTPError: ignored

In [ ]:
df.head()

a   b     c    d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [ ]:
# read Json to csv

In [ ]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [ ]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [ ]:
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [ ]:
# convert Json to csv

In [ ]:
df.to_csv('wine.csv')

In [ ]:
# convert Json to different json formats

df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [ ]:
df.to_json(orient="records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"